project_id = "jlksugbwljricuetwpfn"

[functions.sitemap]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.track-visit]
verify_jwt = false